### ISSUE TITLE
Java tests for pedersen commitment

### ISSUE THREAD

**Issue by dragan2234** [Quadratic-Labs/VerkleTries_Besu#12]
We need a java test for pedersen commitment. We can verify results by comparing [go-verkle](https://github.com/gballet/go-verkle)

**Comment by agnxsh** [comment]
Does any PR have the pedersen comm approved and merged?

**Comment by dragan2234** [comment]
@agnxsh This is ported from besu's initial work:
https://github.com/Quadratic-Labs/VerkleTries_Besu/pull/1/files#diff-fd21dede037e219c0d3339f3e12d3960f1fb56e7bc7650fbba7bd9857ca51f9bR38

It seems like it's a pedersen commitment

**Comment by agnxsh** [comment]
Okay I'll look into it once.

**Comment by namn-grg** [comment]
Hey, is someone working on this? If not, I can work on it.

**Comment by dragan2234** [comment]
hey @namn-grg feel free to start working on it, I think @agnxsh is working on the banderwagon thing right now

**Comment by namn-grg** [comment]
Ok great, can you please assign me this @dragan2234 .

**Comment by dragan2234** [comment]
@namn-grg is there any progress on this? Do you plan working on it or we can re-assign?

**Comment by namn-grg** [comment]
Hey @dragan2234, apologies. Please re-assign to someone else. I am focusing on the Nimbus client for now.

**Comment by dragan2234** [comment]
Done by:
https://github.com/Quadratic-Labs/VerkleTries_Besu/pull/43
