### ISSUE TITLE
fix banderwagon issues

### ISSUE THREAD

**Issue by dragan2234** [Quadratic-Labs/VerkleTries_Besu#22]
Banderwagon is still unfinished. Also a better organization of the code is needed

**Comment by agnxsh** [comment]
hey, @dragan2234, can you walk me through the error once, after you made the changes to the stable build

**Comment by agnxsh** [comment]
hey @dragan2234, as far as i can recall after the stable build change, we have yet to write the Java side of the tests right?

also as far as i can tell, these are the changes/enhancements that are yet to be done:

1. vector commitments for multipoint changes in arkworks from bandersnatch -> banderwagon, so that way it is called should be refactored.
2. refactoring the `jbarray` is yet to be fixed
3. adding more multiproof tests

anything else you can think of pls let me know

**Comment by dragan2234** [comment]
Java tests can be done as separate issue, this issue is for fixing lines 56-78. I've commented out line 58 to fix the build.
https://github.com/Quadratic-Labs/VerkleTries_Besu/blob/main/ipa-multipoint/ipa_multipoint_jni/src/lib.rs#L56

btw, what do you mean by "vector commitments for multipoint changes"? My understanding is that for now we have pedersen commitment in the code and that's it, we still don't have a "multipoint" thing, but let me know your thoughts

**Comment by agnxsh** [comment]
Pedersen for a vector (key-values) is conventionally being called vector commitments, nothing special

**Comment by agnxsh** [comment]
Okay I'll get that snippet fixed asap

**Comment by dragan2234** [comment]
> Pedersen for a vector (key-values) is conventionally being called vector commitments, nothing special

yes, but I think "multipoint" is referring to a different thing - I think multipoint means more or less "merging" multiple Pedersen commitments (which are all polynomials) into one "multipoint" proof. At least that's how I understand it (https://dankradfeist.de/ethereum/2021/06/18/pcs-multiproofs.html )

> We need to provide all intermediate commitments, there is no way around that in Verkle trees, but we only need a single KZG proof in the optimal case. There are efficient multiverification techniques for KZG if all proofs are given to the verifier, but we want to do with just a small constant number of proofs.

This also applies to Pedersen+IPA

**Comment by agnxsh** [comment]
yes yes @dragan2234, that is what i mean as well, basically the homomorphic property of pedersen commitments
