### ISSUE TITLE
make ipa_multipoint lib commit function take up to 256 values

### ISSUE THREAD

**Issue by dragan2234** [Quadratic-Labs/VerkleTries_Besu#3]
comment:
https://github.com/hyperledger/besu-native/pull/56#discussion_r841222851

**Comment by dragan2234** [comment]
it fails when calling the commit func with 256 values although it works for 128 values

**Comment by dragan2234** [comment]
Actually this is done here:
https://github.com/hyperledger/besu-native/blob/main/ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/LibIpaMultipointTest.java#L41

We just need to adapt test case to 256 values instead of 128

**Comment by ch9xy** [comment]
So do you want the value to be 256 instead of 128 in this file ?

https://github.com/Quadratic-Labs/VerkleTries_Besu/blob/main/ipa-multipoint/src/test/java/org/hyperledger/besu/nativelib/ipa_multipoint/LibIpaMultipointTest.java

**Comment by dragan2234** [comment]
Yes, number of children nodes in verkle tries is 256. Specs:
https://notes.ethereum.org/@vbuterin/verkle_tree_eip

**Comment by ch9xy** [comment]
Okay, let me change the value.

**Comment by dragan2234** [comment]
Done by:
https://github.com/Quadratic-Labs/VerkleTries_Besu/pull/43
