### ISSUE TITLE
implement pedersen_hash

### ISSUE THREAD

**Issue by dragan2234** [Quadratic-Labs/VerkleTries_Besu#4]
besides pedersen commitments + IPA, pedersen_hash is also used in verkle tries, so we would need an implementation in Java. Rust reference:
https://github.com/crate-crypto/rust-verkle/blob/master/verkle-spec/src/lib.rs#L35

**Comment by ch9xy** [comment]
I found some code related to this. I would like to get assigned to show you.

**Comment by dragan2234** [comment]
@ch9xy Sure, please. We are learning about all of this stuff so feel free to share any thoughts

**Comment by ch9xy** [comment]
I created a pull request for it.

**Comment by dragan2234** [comment]
Some conclusions:

pedersen hash and pedersen commitments are 2 same things. in this context we are reffering to pedersen hash as an MSM of 4 elements and it's used when we are generating trie-keys, and "pedersen commitment" is actually the same thing, but it's the MSM of 256 values in children nodes

**Comment by dragan2234** [comment]
@ch9xy feel free to investigate more on pedersen hash in verkle tries, and make something meaninful on the repo, you should be able to claim rewards $$ on onlydust.xyz if there's something we can merge

@vbuterin note:
```
def pedersen_hash(inp: bytes) -> bytes32:
    assert len(inp) <= 255 * 16
    # Interpret input as list of 128 bit (16 byte) integers
    ext_input = inp + b"\0" * (255 * 16 - len(inp))
    ints = [2 + 256 * len(inp)] + \
           [int.from_bytes(ext_input[16 * i:16 * (i + 1)]) for i in range(255)]
    return compute_commitment_root(ints).serialize()
```
taken from https://notes.ethereum.org/@vbuterin/verkle_tree_eip

**Comment by ch9xy** [comment]
I'm investigating through it.

**Comment by ch9xy** [comment]
> @ch9xy feel free to investigate more on pedersen hash in verkle tries, and make something meaninful on the repo, you should be able to claim rewards $$ on onlydust.xyz if there's something we can merge
> 
> @vbuterin note:
> 
> ```
> def pedersen_hash(inp: bytes) -> bytes32:
>     assert len(inp) <= 255 * 16
>     # Interpret input as list of 128 bit (16 byte) integers
>     ext_input = inp + b"\0" * (255 * 16 - len(inp))
>     ints = [2 + 256 * len(inp)] + \
>            [int.from_bytes(ext_input[16 * i:16 * (i + 1)]) for i in range(255)]
>     return compute_commitment_root(ints).serialize()
> ```
> 
> taken from https://notes.ethereum.org/@vbuterin/verkle_tree_eip

Do we have any cryptographic library restrictions for the sake of security ?

**Comment by dragan2234** [comment]
hey @ch9xy we have a dedicated telegram group for the development of this library. If you want to learn more about specs of the verkle tries and contribute let me know your contact I can add you (you can contact me on twitter or linkedin)

**Comment by ch9xy** [comment]
> hey @ch9xy we have a dedicated telegram group for the development of this library. If you want to learn more about specs of the verkle tries and contribute let me know your contact I can add you (you can contact me on twitter or linkedin)

I just sent you a connection request in Linkedin

**Comment by dragan2234** [comment]
Done by:
https://github.com/Quadratic-Labs/VerkleTries_Besu/pull/43
